vars: {
  d2-config: {
    layout-engine: elk
  }
}

admin: |md
  ## Admin
  [Person]
| {
  shape: c4-person
}

reseller: |md
  ## Reseller
  [Person]
| {
  shape: c4-person
}

user: |md
  ## User
  [Person]
| {
  shape: c4-person
}

system: |md
  ## Ticketing Software System
  [Software System]

  Allow users to manage and order ticket shows.
| {
  shape: rectangle
  style.fill: "#87CEEB"
  label.near: bottom-left
}

system.resellerDashboard: |md
  ## Reseller Dashboard Web
  [Container: Web Application]

  Web application for resellers to manage tickets.
| {
  shape: rectangle
}

system.resellerCustomWeb: |md
  ## Reseller Custom Web
  [Container: Web Application]

  Custom web application for users to explore and order tickets.
| {
  shape: rectangle
}

system.adminDashboard: |md
  ## Admin Dashboard Web
  [Container: Web Application]

  Web application for admins to manage the ticketing platform.
| {
  shape: rectangle
}

system.gateway: |md
  ## API Gateway
  [Container: Kong Gateway]

  Provide clients to communicate with backend services.
| {
    shape: rectangle
}

coreOrderTicketService: |md
  ## Core Order Ticket Service
  [Software System]
  
  Provide order tickets functionalities.
| {
  shape: rectangle
  style.fill: "#87CEEB"
}

coreExploreTicketService: |md
  ## Core Explore Ticket Service
  [Software System]
  
  Provide explore tickets functionalities.
| {
  shape: rectangle
  style.fill: "#87CEEB"
}

customWebService: |md
  ## Custom Web Service
  [Software System]
  
  Provide explore & order tickets functionalities for custom web.
| {
  shape: rectangle
  style.fill: "#87CEEB"
}

adminService: |md
  ## Admin Service
  [Software System]
  
  Provide platform management functionalities.
| {
  shape: rectangle
  style.fill: "#87CEEB"
}

resellerService: |md
  ## Reseller Service
  [Software System]
  
  Provide reseller management functionalities.
| {
  shape: rectangle
  style.fill: "#87CEEB"
}

resellerSystem: |md
  ## Reseller System
  [Software System]
  
  Reseller system that integrate with ticketing system.
| {
  shape: rectangle 
}

user -> system.resellerCustomWeb: Explore and order tickets for events using
admin -> system.adminDashboard: Manage platform using
reseller -> system.resellerDashboard: Manage tickets using
system.resellerCustomWeb -> system.gateway: "[HTTPS]"
system.adminDashboard -> system.gateway: "[HTTPS]"
system.resellerDashboard -> system.gateway: "[HTTPS]"
resellerSystem -> system.gateway: "Integrate ticketing functionalities\n[HTTPS]"

system.gateway -> resellerService: "Manage tickets using\n[HTTPS]"
system.gateway -> adminService: "Manage platform using\n[HTTPS]"
system.gateway -> customWebService: "Explore & order tickets for custom web using\n[HTTPS]"
system.gateway -> coreExploreTicketService: "Explore tickets using\n[HTTPS]"
system.gateway -> coreOrderTicketService: "Order tickets using\n[HTTPS]"
