softwareSystem: |md
  ## Ticketing Software System
  [Software System]

  Allow users to manage and order ticket shows.
| {
  shape: rectangle
  style.fill: "#87CEEB"
}

system: |md
  ## Admin Service
  [Software System]
  
  Provide platform management functionalities.
| {
  shape: rectangle
  style.fill: "#87CEEB"
  label.near: bottom-left
}

notificationService: |md
  ## Notification Service
  [Software System]
  
  Provide notification functionalities.
| {
  shape: rectangle
  style.fill: "#87CEEB"
}

coreOrderTicketService: |md
  ## Core Order Ticket Service
  [Software System]
  
  Provide order tickets functionalities.
| {
  shape: rectangle
  style.fill: "#87CEEB"
}

resellerService: |md
  ## Reseller Service
  [Software System]
  
  Provide ticket management functionalities.
| {
  shape: rectangle
  style.fill: "#87CEEB"
}


system.adminService: |md
  ## Service API
  [Container: HTTP Service]
  
  Provide platform management functionalities.
| {
  shape: rectangle
}

system.adminDb: |md
  ## Database
  [Container: PostgreSQL]

  Store admin, platform, & reseller data.
| {
  shape: cylinder
}

direction: right

softwareSystem -> system.adminService: "Manage platform using\n[HTTPS]"
system.adminService -> system.adminDb: "Read from and write to\n[PG Protocol]"
system.adminService -> notificationService: {
  label: "Send admin events\n[Kafka Protocol]"
  style.stroke-dash: 3
}
resellerService -> system.adminService: {
  label: "Send reseller events\n[Kafka Protocol]"
  style.stroke-dash: 3
}
coreOrderTicketService -> system.adminService: {
  label: "Send order ticket events\n[Kafka Protocol]"
  style.stroke-dash: 3
}
