vars: {
  d2-config: {
    layout-engine: elk
  }
}

admin: {
  label: Admin
  shape: c4-person
  style.fill: "#fab1a0"
}

reseller: {
  label: Reseller
  shape: c4-person
  style.fill: "#fab1a0"
}

user: {
  label: User
  shape: c4-person
  style.fill: "#fab1a0"
}

resellerDashboard: Reseller Dashboard
resellerCustomWeb: Reseller Custom Web
adminDashboard: Admin Dashboard
resellerSystem: {
  label: Reseller System
  style.fill: "#fab1a0"
} 

gateway: { 
  label: API Gateway
  shape: hexagon
}

reseller -> resellerDashboard
user -> resellerCustomWeb
admin -> adminDashboard

coreOrderTicketService: Core Order Ticket Service
coreExploreTicketService: Core Explore Ticket Service
resellerService: Reseller Service
adminService: Admin Service
notificationService: Notification Service
customWebService: Custom Web Service

database: {
  label: Database
  shape: cylinder
}

resellerDashboard -> gateway: Manage tickets
resellerCustomWeb -> gateway: Browse & order tickets
adminDashboard -> gateway: Manage platform
resellerSystem -> gateway: Integrate with ticketing platform
gateway -> coreOrderTicketService
gateway -> coreExploreTicketService
gateway -> resellerService
gateway -> adminService
gateway -> customWebService
coreExploreTicketService -> database
customWebService -> database
customWebService -> coreExploreTicketService
customWebService -> coreOrderTicketService
adminService -> database
coreOrderTicketService -> database
resellerService -> database
adminService -> notificationService
coreOrderTicketService -> notificationService
resellerService -> notificationService 
notificationService -> resellerSystem
