countryA: {
  label: "Cluster: Country A"
}

cityA: {
  label: "Cluster: City A"
}

cityB: {
  label: "Cluster: City B"
}

districtA: {
  label: "Cluster: District A"
}

districtB: {
  label: "Cluster: District B"
}

districtC: {
  label: "Cluster: District C"
}

districtD: {
  label: "Cluster: District D"
}

addressA: {
  label: "Address A"
}

addressB: {
  label: "Address B"
}

addressC: {
  label: "Address C"
}

addressD: {
  label: "Address D"
}

addressE: {
  label: "Address E"
}

addressF: {
  label: "Address F"
}

addressG: {
  label: "Address G"
}

addressH: {
  label: "Address H"
}

addressI: {
  label: "Address I"
}

addressJ: {
  label: "Address J"
}

addressK: {
  label: "Address K"
}

addressL: {
  label: "Address L"
}

addressM: {
  label: "Address M"
}

addressN: {
  label: "Address N"
}

addressO: {
  label: "Address O"
}

addressP: {
  label: "Address P"
}

countryA -> cityA
countryA -> cityB
cityA -> districtA
cityA -> districtB
cityB -> districtC
cityB -> districtD
districtA -> addressA
districtA -> addressB
districtA -> addressC
districtA -> addressD
districtB -> addressE
districtB -> addressF
districtB -> addressG
districtB -> addressH
districtC -> addressI
districtC -> addressJ
districtC -> addressK
districtC -> addressL
districtD -> addressM
districtD -> addressN
districtD -> addressO
districtD -> addressP
