vars: {
  d2-config: {
    layout-engine: elk
  }
}

guest: |md
  ## Guest
  [person]

  Hotel guest
| {
  shape: c4-person
}

reservationStaff: |md
  ## Reservation Staff
  [person]

  Staff member who handles reservations
| {
  shape: c4-person
}

cleaningStaff: |md
  ## Cleaning Staff
  [person]

  Staff member who handle housekeeping
| {
  shape: c4-person
}

newReservationSystem: |md
  ## New Reservation System
  [Software System]

  System for handling guest reservation with state-of-the-art housekeeping management.
| {
  shape: rectangle
  style.fill: "#87CEEB"
}

oldReservationSystem: |md
  ## Old Reservation System
  [Software System]

  Legacy system for handling room management, payment, etc.
| {
  shape: rectangle
}

smartLockSystem: |md
  ## Smart Lock System
  [Software System]

  System for managing smart locks on guest room doors.
| {
  shape: rectangle
}

ses: |md
  ## Amazon SES
  [Software System]

  Service to send email notifications.
| {
  shape: rectangle
}

guest -> newReservationSystem: login, register, create reservation, lock/unlock room smart lock, & request housekeeping
guest -> oldReservationSystem: complete payment
reservationStaff -> newReservationSystem: manage guest reservations, manage housekeeping, re-generate payment links, manage temporary guest credentials, & view lock/unlock room logs.
cleaningStaff -> newReservationSystem: view & update housekeeping tasks
reservationStaff -> oldReservationSystem: manage room data
newReservationSystem -> oldReservationSystem: {
  label: "reservation created\n[Pub/Sub]"
  style.stroke-dash: 3
}
newReservationSystem -> smartLockSystem: "lock/unlock room smart lock\n[HTTPS]"
smartLockSystem -> newReservationSystem: {
  label: "room lock/unlock state updated\n[Pub/Sub]"
  style.stroke-dash: 3
}
oldReservationSystem -> newReservationSystem: {
  label: "room state updated, payment created\n[Pub/Sub]"
  style.stroke-dash: 3
}
newReservationSystem -> ses: "send email notifications\n[HTTPS]"
ses -> guest: email notifications
