guest: |md
  ## Guest
  [person]

  Hotel guest
| {
  shape: c4-person
}

reservationStaff: |md
  ## Reservation Staff
  [person]

  Staff member who handles reservations
| {
  shape: c4-person
}

cleaningStaff: |md
  ## Cleaning Staff
  [person]

  Staff member who handle housekeeping
| {
  shape: c4-person
}

newReservationSystem: |md
  ## New Reservation System
  [Software System]

  System for handling guest reservation with state-of-the-art housekeeping management.
| {
  shape: rectangle
  style.fill: "#87CEEB"
}

oldReservationSystem: |md
  ## Old Reservation System
  [Software System]

  Legacy system for handling room management, payment, etc.
| {
  shape: rectangle
}

smartLockSystem: |md
  ## Smart Lock System
  [Software System]

  System for managing smart locks on guest room doors.
| {
  shape: rectangle
}

ses: |md
  ## Amazon SES
  [Software System]

  Service to send email notifications.
| {
  shape: rectangle
}

guest -> newReservationSystem: Create reservation
reservationStaff -> newReservationSystem: Manage guest reservations & housekeeping
cleaningStaff -> newReservationSystem: Handle Housekeeping tasks
newReservationSystem -> smartLockSystem: "Lock/unlock room smart lock\n[HTTPS]"
smartLockSystem -> newReservationSystem: {
  label: "Publish topics to\n[Pub/Sub Protocol]"
  style.stroke-dash: 3
}
oldReservationSystem -> newReservationSystem: {
  label: "Publish & subscribe topics to/from\n[PubSub Protocol]"
  style.stroke-dash: 3
}
newReservationSystem -> ses: "Send email notifications\n[HTTPS]"
